# Generated by Django 4.2.5 on 2024-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0002_controlpoints_na'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoints_na',
            name='level1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlpoints_na',
            name='level2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlpoints_na',
            name='level3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
