# Generated by Django 4.2.5 on 2024-05-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0003_controlpoints_na_level1_controlpoints_na_level2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlpoints_na',
            old_name='level1',
            new_name='sl1_time',
        ),
        migrations.RenameField(
            model_name='controlpoints_na',
            old_name='level2',
            new_name='sl2_time',
        ),
        migrations.RenameField(
            model_name='controlpoints_na',
            old_name='level3',
            new_name='sl3_time',
        ),
    ]
