# Generated by Django 4.2.5 on 2024-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0004_rename_level1_controlpoints_na_sl1_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoints_na',
            name='sl1_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlpoints_na',
            name='sl2_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlpoints_na',
            name='sl3_time',
            field=models.IntegerField(default=0),
        ),
    ]
