# Generated by Django 4.2.5 on 2024-06-21 21:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0005_alter_controlpoints_na_sl1_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlpoints_AP',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('count', models.CharField(max_length=100, null=True)),
                ('sl1_time', models.IntegerField(default=0)),
                ('sl2_time', models.IntegerField(default=0)),
                ('sl3_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Controlpoints_EU',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('count', models.CharField(max_length=100, null=True)),
                ('sl1_time', models.IntegerField(default=0)),
                ('sl2_time', models.IntegerField(default=0)),
                ('sl3_time', models.IntegerField(default=0)),
            ],
        ),
    ]
