version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/Users/dj/Documents/Backend/geobackend
    ports:
      - 8000:8000

  postgis:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: dj
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  